# Site settings
title: Gnaneswar Villuri
general_email: villurignanesh@gmail.com
academic_email: gnaneswar.villuri@stonybrook.edu

description: > # this means to ignore newlines until "baseurl:"
  Passionate PhD researcher and Machine Learning Engineer with a focus on scalable ML algorithms, deep learning, and reinforcement learning for multi-modal data analysis.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://villurignanesh.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: villurignanesh
linkedin_username: villurignanesh
facebook_username: villurignanesh
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title